version: ~> 1.0
git:
  depth: 1
  quiet: true
language: java
jdk:
- openjdk11
branches:
  only:
  - develop
  - support/.*
  - master
cache:
  directories:
    - $HOME/.m2
notifications:
  irc:
    channels:
    - chat.freenode.net#craftercms
    use_notice: true
    skip_join: true
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
script:
- if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c  "mvn deploy --settings
  .travis-settings.xml";  fi
- if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install" ;fi
env:
  global:
  - secure: Apa4XXXOk59AQQqXMg+FpwgYfzlWsK1UpOBMnauc+joBUbR0dYtACWVCd0D7+pAoGlj/Rh6d8hrLLOiBwl7jYlFZyqvRMXVO0C0XF5vXVBe6CvXjtCUNpSQPnKNYFJn0ZK+8tfjvn/b7aY1eQ+xveiny5pn7R0o4GchkXv6XsrlqmhXpwcWbAM9kBIP5MHGrvSLxxoAIzRcmT7WcL+ukcr02FYwvrb4uQRq43AeNouYP1fdzv/45jcVItlQ+WiN2ZGil5ZQyZJO2x6H2xa2aDbmG0fZ5Z9Q5u4r1SLNCYkg1SjmO42IItlxQg5yujNKF+tv3IGtGL7t7CmFWkjehJLsqReIblglaNzJJ2TdBHHtHXZwXLdSsoTYh2EcNtR2tVCgbM09PE6i/f7bVriLkWdHfEnbAhEEBvcIK8/uVvD/hvPDf9YbZNxeb7XAQ1hAC6NwOxITHmomK53OZllnvkTHYUYzCTJ5XCP8AxlzQ74LlUpMaPCP879fxMrs894TY6n9BUolKBNuDj5K0B5bDb3HwHIxhWgTgr1Y2/9xbvgqjuwn7nxwsjg/i1qsPWAd8AErFbvtomTC3le0SqxyhSOE4FIeS6rjADOLZXqB3GcwKEEpX5js5bvIzPhPPZxig7dyaCaQiYC3Ie9A7hHAuqogM/jnA7QdHIhIYWlpHnIU=
  - secure: h9HZ6lqQdTHzdC7iJLzOLLQ8Pe+wsA3MuscuZVu3M5N7weE60iTbVktPEa3ngkCfOR0z25pPuK5zCrzKEfVZymis3k4hyV1raIR2w9DayCRREmxrCOoCaCTiV7ykABmkMJz0TUzphu7GVYBAje3JEBETJC/oFcUwvd/a4wODfzdchO1z+5w7Q7rGtt6/4br2zoi751sD0F4Lp/dHrQdO++0Qx7haB98B07Azp0+KoZJ6z4yWqu9bk83D5suTRJ9CVaLLlQjF5h9pbow8TVBKnAP9YhYLXMeM/b+mRO3PfEoWGnMgrLSLrJLClw4Viy6Egijo0WaXHYFUol0r1EYJ4dBKwWI4qsEYrmn7FVBJlUmB09eVs1BCGOr1Dy9sFEYBfa6Tm255hCmN7Qks2MOFMhM/d/+EUtwp/gkaS10zgMR++r4Xg2ZhmrY3nrYi+x6zpJPPDyCCg6ddNzNIP/FySqgHs1Ks/T/PpnrXKRI4TTOtmD4IN9DelXk9jPEHM30Bjw/1u93fzYVYPMjp8qbHp6yKNyB/a1zhF2mgo51xtGUA4krUn1g6o0tLJ8ovI6Q/amKdm+OMHquqVSGhuLrSa/sV9sr2StVWNJlgkhRlpMVknae7zcyuYMO3W0PPRJX2xag1tDuKmwkS+6wok8VyFiSLI4+hBOXz5DLTJ11vbTc=
